apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-registry
  namespace: eu-health-interop-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: de-registry
  template:
    metadata:
      labels:
        app: de-registry
    spec:
      containers:
        - name: de-registry
          image: de-registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # ---- SERVICE ----
            - name: OTEL_SERVICE_NAME
              value: de-registry

            # ---- TRACES ----
            - name: OTEL_TRACES_EXPORTER
              value: otlp

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc

            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317

            # ---- DESABILITAR OUTROS EXPORTERS ----
            - name: OTEL_METRICS_EXPORTER
              value: none

            - name: OTEL_LOGS_EXPORTER
              value: none

            # ---- RESOURCE ATTRIBUTES ----
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=eu-health,service.version=1.0.0,deployment.environment=lab
---
apiVersion: v1
kind: Service
metadata:
  name: de-registry
  namespace: eu-health-interop-lab
spec:
  selector:
    app: de-registry
  ports:
    - port: 8000
      targetPort: 8000
